### ISSUE TITLE
A few compile warnings

### ISSUE THREAD

**Issue by thinkyhead** [teemuatlut/TMCStepper#1]
In the Travis CI test for Marlin we see this [when building](https://travis-ci.org/MarlinFirmware/Marlin/builds/258431141?utm_source=github_status&utm_medium=notification):

```
.piolibdeps/TMC2130Stepper/src/source/TMC2130Stepper.cpp: In member function 'uint16_t TMC2130Stepper::microsteps()':
.piolibdeps/TMC2130Stepper/src/source/TMC2130Stepper.cpp:290:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
.piolibdeps/TMC2130Stepper/src/source/TMC2130Stepper.cpp: In member function 'uint8_t TMC2130Stepper::blank_time()':
.piolibdeps/TMC2130Stepper/src/source/TMC2130Stepper.cpp:308:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
.piolibdeps/TMC2130Stepper/src/source/TMC2130Stepper.cpp: In member function 'uint8_t TMC2130Stepper::sg_current_decrease()':
.piolibdeps/TMC2130Stepper/src/source/TMC2130Stepper.cpp:331:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
```

**Comment by teemuatlut** [comment]
I've pushed a fix and reran the Travis test.

For clarity I'd like to note that this is not the library Marlin is using just yet. This is an attempt to bring the 2130, 2208 and 5130 (TRAMS) under one 'master'-library.

I've also already got the narrowing conversion warnings fixed but that'll be included the next time I propose an update to everything Trinamic.
