### ISSUE TITLE
Marlin build for LPC1768 broken by recent commit

### ISSUE THREAD

**Issue by Fabi0San** [teemuatlut/TMCStepper#102]
platformio build of Marlin for LPC1768 architecture was broken by
https://github.com/teemuatlut/TMCStepper/commit/a9187feee034c97ec292cf916d3a12d100774b0d

**Comment by teemuatlut** [comment]
Update your platform.

**Comment by Fabi0San** [comment]
Sorry, my bad.
https://github.com/MarlinFirmware/Marlin/commit/8e7d1004cf33689b189a3b27f9aa1aebc1a74715
