### ISSUE TITLE
Need help adding TMC driver

### ISSUE THREAD

**Issue by Mboss32** [teemuatlut/TMCStepper#118]
First off, this is a great Library and thank you for all the work!  I am trying to add the new TMC2590 to the library but am a bit overwhelmed.  Anybody have a good place that I should start? It looks like the TMC2590 is very similar in registers as the TMC2660 so maybe a copy/paste and modify is the best route? 

Thanks!

**Comment by teemuatlut** [comment]
Use inheritance.
```cpp
class TMC2590 : public TMC2660Stepper {
  ...
};
```
Add what you need to and overload where there are differences.
