### ISSUE TITLE
TMC5160 SilentStepStick in spi mode?

### ISSUE THREAD

**Issue by nilsgraebner** [teemuatlut/TMCStepper#121]
Hello,
it is more a question than an issue. I am wondering if it is possible to use the TMC5160 SilentStepStick in spi mode. So that there is no need for the step and dir connection. As far as I understood all the examples the velocity is defined by the pulse frequency which is generated by the Arduini. At https://learn.watterott.com/silentstepstick/comparison/ is written that the TMC5160 is able to work with spi connection or is this just for the setup?

**Comment by teemuatlut** [comment]
Yes it is possible. See chapter 12 in the datasheet.

**Comment by nilsgraebner** [comment]
thanks!
but then is the next question how? and is it possible with this library? maybe someone has an example code for this.

**Comment by teemuatlut** [comment]
I'm not aware of any examples.
The ramp generator is described in the datasheet and the register relating to it are in chapter 6.3.1.
Yes the library does expose the necessary register calls.

**Comment by nilsgraebner** [comment]
ok so then i have to do something like integrating this register to your library. i will try to do my best
