### ISSUE TITLE
2208 & 2209 Unresponsive After Library Update

### ISSUE THREAD

**Issue by andrewtreas** [teemuatlut/TMCStepper#123]
I have an SKR 1.3 running Marlin 2.0.5.x and was previously using TMC2208's which worked pretty well. Yesterday I received 2209's and tried to get them running but in the process somehow screwed everything up. While I was editing my code in Atom for a re-flash, I updated my libraries. I  always save my .bin files before building so when my printer would respond in every other way besides being able to move its steppers, I re-flashed with an old version and installed my old 2208's. They responded fine which points the finger at my libraries. I believe the TMCStepper library I was running before upgrading was 4.3 but I could be wrong. I would like to know if there is a way to downgrade library versions so I can test this theory. If any files will be of help in solving this issue, please let me know. Thank you in advance!

**Comment by jafidod** [comment]
Try to search for "#TMCStepper@>=0.6.1,<1.0.0" in platformio.ini file and replace it by "TMCStepper@>=0.4.3,<0.4.4". It should be there twice.

You might encounter some errors in file TMC_platforms.h during compilation. The compiler tells you what is wrong in such a case. In my case was necessary to specify namespace LPC176x in front of few code lines.

>   #define writeMOSI_H LPC176x::gpio_set(mosi_pin)
>   #define writeMOSI_L LPC176x::gpio_clear(mosi_pin)
>   #define writeSCK_H LPC176x::gpio_set(sck_pin)
>   #define writeSCK_L LPC176x::gpio_clear(sck_pin)
>   #define readMISO LPC176x::gpio_get(miso_pin)
