### ISSUE TITLE
Integrated Motion Controller in 5160, 5130?

### ISSUE THREAD

**Issue by PMTaylor** [teemuatlut/TMCStepper#147]
Is anyone working on writing code for the integrated motion controller in the 5160, 5130? 

Is there another Arduino compatible library that does offer this? Any fork of TMCStepper we're aware of there people are implementing  or have already implemented this?

I've written an implementation in Python (targeted at the RasPi), but also want a solution for Arduino. If no one is working on it, and there are no forks to join, i will start building this (slowly) into TMCStepper, but i'd prefer it if i can join an existing effort.
Thoughts?
I understand that the standard use case for the drivers are in 3d printers, but for more general motion applications, the integrated motion controller would be great.

**Comment by teemuatlut** [comment]
This isn't really something that would be part of the library other than as an example.
The library provides an interface for communicating with the driver and then you'd write your application to make use of that interface. If you've noticed a missing register call method please do tell but I do believe all of them should be in place and you can use the library as is.
