### ISSUE TITLE
TMC5160 wrong speed in velocity mode?

### ISSUE THREAD

**Issue by segelkma** [teemuatlut/TMCStepper#176]
Hey there,
got one TMC5130 v1.5 Board, running a Nema 17 motor (200 steps/rev) via SPI. I first tested ramp mode 0 and when I set xTarget to 200*256 (256 = stepping) the motor did a 360° turn. In velocity mode however, when I set the speed to 200*256, it does not make a full turn per second. Using the attached script, it is more like 265°/s. The stepping does not seem to have any influence on this.
Am I just missing something here?

```cpp
#include "TMCStepper.h"

uint16_t csPin = 44;
uint16_t steps = 256;
float r_sense = 0.075;

TMC5130Stepper stepper = TMC5130Stepper(csPin, r_sense);

void setup() {
  
  delay(250);

  pinMode(csPin, OUTPUT);
  digitalWrite(csPin, HIGH);

  SPI.begin();

  stepper.toff(3);
  stepper.rms_current(700);
  stepper.en_pwm_mode(false);

  stepper.microsteps(steps);

  stepper.AMAX(UINT16_MAX);
  stepper.RAMPMODE(1);

}

void loop() {
  
  delay(1000);
  stepper.VMAX(200 * steps);
  delay(1000);
  stepper.VMAX(0);
  
}
```

**Comment by teemuatlut** [comment]
Since you're only letting it spin for about a second, you need to account for acceleration as well. Even at 16bit max it's not instant as your target velocity is 51200.

**Comment by segelkma** [comment]
Thanks for your quick reply. I forgot to mention that I also had it run with that speed for a long time and measured by hand the revs per time. It was 10 revs in about 14 seconds. I measured multiple times, also trying different configurations, for example en_pwm_mode set to true

**Comment by segelkma** [comment]
I checked the code again and I could not find any reason for this to happen. A bug in the library seems very unlikely as far as I can tell, since all it does is send the data as it is. So this leaves a wrong configuration or a bug in the stepper firmware (which also seems very unlikely...).

So I checked the 6130 data sheet but could not find any hint. I also contacted trinamic but they seem to have long response times at the moment. So if one has any idea it is much appreciated.

**Comment by segelkma** [comment]
VMAX is not Steps/s but Steps/t
```
Time reference t for velocities: t = 2^24 / fCLK
Time reference ta² for accelerations: ta² = 2^41 / (fCLK)²
```

**Comment by rena2019** [comment]
What rps do you expect if you set VMAX to 51200 (with fCLK=12MHz)? 1.398 rps? I measured 0.625 rps

**Comment by SobhanAbedi** [comment]
Not exactly. for a fCLK of 12MHz, you get t = 1.39810. Thus you should be expecting 51200 microsteps (1 rotation) in 1.39810 seconds. Therefore you get a rps equal to 0.71526 which is still larger than what you get. But when you consider acceleration it  becomes reasonable and as you mentioned in a constant velocity 
> It was 10 revs in about 14 seconds.

which is the same as expected value of 1 rotation in 1.39810 seconds
