### ISSUE TITLE
Debug code for TCM2130

### ISSUE THREAD

**Issue by simonemarin** [teemuatlut/TMCStepper#187]
Hallo I am struggling here with temperature issue and weird behaviour, is there a debugging code just to see what SPI can say about firmware version, temperature etc.? (for TCM2130)

**Comment by teemuatlut** [comment]
Driver firmware version can be read from IOIN register or with `.version()`.
For temperature there are two binary sensors; one for overtemperature (150C) and one for pre-warn (120C). These can be read in the DRV_STATUS register or with `.ot()` and `.otpw()`.
