### ISSUE TITLE
Why is the TMC2208 stepper address hardcoded?

### ISSUE THREAD

**Issue by aguaviva** [teemuatlut/TMCStepper#263]
It looks like the address is set here 

https://github.com/teemuatlut/TMCStepper/blob/c425c40f0adfa24c1c21ce7d6428bcffc2c921ae/src/TMCStepper.h#L828

And TMC2208_SLAVE_ADDR is hard coded to 0. Why is that? Could it be set to values from 0 to 3? This would help reduce pin usage as up to 4 drivers would be able to share the same UART.

 I might be missing something though but all looks like addressing should just work and have a similar implementation as in the TMC2209

Thanks!

**Comment by teemuatlut** [comment]
The TMC2208 doesn't support addressing the same way 2209 does.

**Comment by aguaviva** [comment]
You are right, thanks though :)
