### ISSUE TITLE
LPC1768 TMC2130 steppers no longer move with Marlin 2.0.x

### ISSUE THREAD

**Issue by dp250f** [teemuatlut/TMCStepper#27]
I'm not sure if this is a Marlin bug or a TMCStepper bug, so I'm submitting this in both places.

### Description

Was using repository from 5/11/2019, stepper motors all worked (TMCStepper 0.3.2)
Cloned new repository form 5/18/2019, steppers no longer move. (TMCStepper 0.3.3)

### Steps to Reproduce

1. Clone 2.0.x repository from today, configure and compile for LPC1768 (BOARD_BIGTREE_SKR_V1_3) and TMC2130 drivers in SPI mode

**Expected behavior:** Steppers move

**Actual behavior:** Steppers don't move

#### Additional Information

This seemed to work fine from when I had compiled it earlier this week, using the build from 5/11/2019.   If I specify TMCStepper@0.3.2 in my platformio.ini, it works like it did before.
[bug report.zip](https://github.com/teemuatlut/TMCStepper/files/3194779/bug.report.zip)

I have also submitted this at the Marlin repository:
https://github.com/MarlinFirmware/Marlin/issues/14059

**Comment by teemuatlut** [comment]
Let me know if v0.3.4 fixes things for you. It should hit PIO Library manager in a day or two.

**Comment by dp250f** [comment]
Thank you!  Version 0.3.4 is working.
