### ISSUE TITLE
TMC2660 dummy data issue

### ISSUE THREAD

**Issue by stefan85** [teemuatlut/TMCStepper#34]
Hi,

I have problem with using the TMC2660 in combination with an LPC1769.
When using Marlin, the speed seems way off. I think the registers aren't written correctly.
After some experimentation I found that commit 769273c is the cause of this.

As a test, I changed it back to the way it was before: uint32_t dummy = 0b010UL<<17;
This solved it for me. 

Could you implement this fix in a future release?

Thanks in advance.

**Comment by teemuatlut** [comment]
Thanks. I'll revert the change for next release.

**Comment by teemuatlut** [comment]
https://github.com/teemuatlut/TMCStepper/releases/tag/v0.4.0
