### ISSUE TITLE
Compatibility of TMC2209 with Linear advance on Marlin

### ISSUE THREAD

**Issue by Gerggg** [teemuatlut/TMCStepper#45]
Does the addition of the TMC2209 correct the compatibility problem we encounter between TMC2208 and linear advance? as a reminder, the extruder motor shuts off when TMC2208 is used with Marlin's Linear Advance feature.

**Comment by teemuatlut** [comment]
No there should be no difference in that.
Square step mode would have a much better likelihood of correcting the behavior.

**Comment by Gerggg** [comment]
Thank you for your answer, can you specify the option to activate the Square step mode ?

**Comment by teemuatlut** [comment]
https://github.com/MarlinFirmware/Marlin/blob/dd06017f642b0396389e85796e447ecee47fdd4b/Marlin/Configuration_adv.h#L1833-L1837

**Comment by Gerggg** [comment]
Great, I'll try this. Thank you.

**Comment by drewzh** [comment]
> Great, I'll try this. Thank you.

Out of curiosity, as I'm about to start looking at linear advance - did you have any luck?

**Comment by Gerggg** [comment]
yes, it works perfectly well.  I just have a strange noise when retracting but otherwise it's absolute silence.

**Comment by Gerggg** [comment]
good sorry but if the noise level is good, the level of inpression quality I did not have a good result with the TMC2209 (a lot of layer shift)

**Comment by Gerggg** [comment]
The problem has been fixed since version 0.4.5.
