### ISSUE TITLE
problem update

### ISSUE THREAD

**Issue by gauix4** [teemuatlut/TMCStepper#46]
<img width="1680" alt="Capture d’écran 2019-06-20 à 22 15 36" src="https://user-images.githubusercontent.com/23041016/59878790-7ac50880-93a9-11e9-8dcf-5ac4e5fad514.png">

I do not understand I'm fine doing PIO update it is well updated but when I debug it does not take into account

**Comment by teemuatlut** [comment]
Check your `platformio.ini` file.

**Comment by gauix4** [comment]
@teemuatlut I left the original TMCStepper@<1.0.0
I tested with https://github.com/teemuatlut/TMCStepper/archive/master.zip
it does not change much

**Comment by gauix4** [comment]
<img width="1680" alt="Capture d’écran 2019-06-20 à 22 32 59" src="https://user-images.githubusercontent.com/23041016/59879616-6550de00-93ab-11e9-8247-c975fb874547.png">

**Comment by teemuatlut** [comment]
Try deleting the .pioenvs and .piolibdeps folders. That should prompt PIO to redownload all dependencies.

**Comment by gauix4** [comment]
@teemuatlut  I do not have access to his files on Mac by searching a little on Google and on the right to the left I just found that Atom is not compatible with Mac above IOS10

**Comment by gauix4** [comment]
@teemuatlut  it does not change anything

**Comment by teemuatlut** [comment]
I see you've highlighted the line 35 on the pio file, but that's not the section LPC is using.
Go further down to LPC1768 section and make the changes there.

https://github.com/MarlinFirmware/Marlin/blob/4df4c47994f248428ae30218800803e467327b6e/platformio.ini#L149-L169

**Comment by gauix4** [comment]
@teemuatlut yes yes I know I had just taken the first one that had come

**Comment by gauix4** [comment]
I think it will go so fast to take back a blank Marlin and complete it

**Comment by teemuatlut** [comment]
You may also encounter issues using PIO on Atom and switching to Visual Code is recommended as it is their preferred platform.

**Comment by gauix4** [comment]
@teemuatlut yes that's what I saw more I'm on Mac and they stopped the development at iOS10

**Comment by gauix4** [comment]
@teemuatlut  after several tests the TMC5160 that I activate or not STEALTHCHOP it does not change anything makes noise

**Comment by gauix4** [comment]
@teemuatlut 
first start the engines are silent you turn as I should disconnect the power I reconnect they make a lot of noise and nothing works.
I have beautiful re flash they make a lot of noise now
it is to understand nothing
