### ISSUE TITLE
Help with TMC5160

### ISSUE THREAD

**Issue by thalesfsp** [teemuatlut/TMCStepper#53]
@teemuatlut do you have an email where I can reach you out? I need help sending SPI commands to the TMC5160. Thank you, appreciate your time and help!

**Comment by teemuatlut** [comment]
If you don't want to share the information or your project publicly:
teemu.mantykallio (at) live.fi

Though mostly you can get pretty far with the examples and information for TMC2130 as they share the same SPI configuration.

**Comment by thalesfsp** [comment]
Thank you! I will send you one email with more detail :)
