### ISSUE TITLE
TMC5160 ESP32 rms_current settings

### ISSUE THREAD

**Issue by danielawd** [teemuatlut/TMCStepper#65]
Hi

I get it working but it overheat if i put current to 3A!
ESP32 
[Watterott TMC5160 SILENTSTEPSTICK v1.3](https://learn.watterott.com/silentstepstick/pinconfig/tmc5160/)
24v 10A powersupply
[Nema23 3A Stepper 23HS30-3004S](https://www.amazon.ca/gp/product/B00O6IQBKK/ref=ppx_yo_dt_b_search_asin_image?ie=UTF8&psc=1)

if i put rms_current to 3000 i get hot TMC5160 and Stepper both over 55 celcius quickly!
if i put rms_current to 600 it is colder but am i losing torque underpowering my 3A stepper?
```

/**
   Author Teemu Mäntykallio
   Initializes the library and runs the stepper motor.
*/
#include <TMCStepper.h>
#define EN_PIN    16  // RX2 esp32 
#define DIR_PIN   2  //5
#define STEP_PIN  15
#define CS_PIN   12

#define R_SENSE 0.075 // Match to your driver
// SilentStepStick series use 0.11
// UltiMachine Einsy and Archim2 boards use 0.2
// Panucatt BSD2660 uses 0.1
// Watterott TMC5160 uses 0.075

TMC5160Stepper driver = TMC5160Stepper(CS_PIN, R_SENSE);

#include <AccelStepper.h>
AccelStepper stepper = AccelStepper(stepper.DRIVER, STEP_PIN, DIR_PIN);

void setup() {
  SPI.begin();
  Serial.begin(9600);
  while (!Serial);
  Serial.println("Start...");
  pinMode(CS_PIN, OUTPUT);
  digitalWrite(CS_PIN, HIGH);
  driver.begin();             // Initiate pins and registeries
  driver.rms_current(600);    // Set stepper current to 600mA. The command is the same as command TMC2130.setCurrent(600, 0.11, 0.5);
  driver.en_pwm_mode(1);      // Enable extremely quiet stepping
  driver.pwm_autoscale(1);
  driver.microsteps(16);

  stepper.setMaxSpeed(10);
  stepper.setAcceleration(2);
  stepper.setMinPulseWidth(100);
  stepper.moveTo(60);
  stepper.setEnablePin(EN_PIN);
  stepper.setPinsInverted(false, false, true);
  stepper.enableOutputs();
}

void loop() {

  if (stepper.distanceToGo() == 0)
    stepper.moveTo(-stepper.currentPosition());

  stepper.run();
}

```

**Comment by teemuatlut** [comment]
https://learn.watterott.com/silentstepstick/faq/#how-to-cool-the-silentstepsticks

> **TMC5160**: For currents up to 2A RMS a good air circulation is enough and for higher currents a cooling fan is needed. On the TMC5160 the external MosFets and shunt resistors have to be cooled.

Torque is relative to coil currents, so yes; lower current means lower torque.
But it's not a problem unless you're skipping steps. And not due to hardware issues. You need to find a good balance between thermals and the required torque.
