### ISSUE TITLE
TMC5160Stepper.cpp:  PWMCONF_register.sr is declared twice?

### ISSUE THREAD

**Issue by wesk-ms** [teemuatlut/TMCStepper#79]
Hi @teemuatlut,

Thanks again for your hard work on this repo!

In TMC5160Stepper.cpp, PWMCONF_register.sr appears to be initialized twice.

First, on line 14:  PWMCONF_register.sr = 0x00050480;
Then, on line 39:  PWMCONF_register.sr = 0xC40C001E;

It appears that line 14 is correct and line 39 can be removed.  Am I interpreting this correctly?

Thanks!
Wes

**Comment by teemuatlut** [comment]
Fixed https://github.com/teemuatlut/TMCStepper/commit/18adb9518a3fc50d1963a0879801b8b574fd3f53
