### ISSUE TITLE
driver.cs2rms(driver.SGTHRS()) seemingly not making sense

### ISSUE THREAD

**Issue by hidoba** [teemuatlut/TMCStepper#83]
Taken from example file "StallGuard_TMC2209.ino", the line
`Serial.println(driver.cs2rms(driver.SGTHRS()), DEC);`
seems to take the value of SGTHRS (current threshold for stall detection), a value from 0 to 255, and convert it into current by the formula for converting CS (number from 0 to 31) that is controlling the rms current of the motor.
Seems like they are totally unrelated, the code might have had a different original intention?

**Comment by teemuatlut** [comment]
You are absolutely correct on that one.

**Comment by teemuatlut** [comment]
https://github.com/teemuatlut/TMCStepper/commit/1bf45c0655258c80973ccf682c13911fbce359c5
