### ISSUE TITLE
TMC262 Support

### ISSUE THREAD

**Issue by phodgers** [teemuatlut/TMCStepper#88]
Hi,

I'm wondering if the TMC262 is supported (perhaps it is the same config as one of the other listed models)? I have seen [this TMC262 break out board](https://uk.farnell.com/trinamic/tmc262-bob60/breakout-board-60v-stepper-predriver/dp/3210872) but not sure if is supported by TMCStepper yet, or if support could be added?

Thanks

**Comment by teemuatlut** [comment]
The 2660 is based on the 26x designs and share the same interface and registers.
But I'd suggest picking a much more modern solution like the 5160.

**Comment by phodgers** [comment]
OK, thanks for the steer.
